version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "19:30"
      timezone: "Europe/Paris"
    allow:
      - dependency-name: "core/cache_subsystem/hpdcache"
      - dependency-name: "verif/core-v-verif"
      - dependency-name: "verif/sim/dv"
    labels: []
