name: Add Test Comment on Push

on:
  push:
    branches-ignore:
      - main  # Avoid infinite loops

jobs:
  add-test-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get modified files
        id: changed-files
        run: |
          # List modified files from the commit
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > modified_files.txt
          cat modified_files.txt
          
      - name: Setup GitHub CLI
        run: |
          # Authenticate gh CLI with the workflow token
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Add test comment and create PR
        run: |
          # Create a new branch
          BRANCH_NAME="add-test-comment-$(date +%s)"
          git checkout -b $BRANCH_NAME
          
          # Add test to each modified file
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Adding test to $file"
              echo -e "\ntest" >> "$file"
            fi
          done < modified_files.txt
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Commit changes
          git add .
          git commit -m "Add test comment to modified files"
          
          # Push branch using a token with proper permissions
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH_NAME
          
          # Create PR using GitHub CLI
          gh pr create --base main --head $BRANCH_NAME --title "Add test comment to modified files" --body "This PR adds a 'test' comment at the end of files modified in the latest push." || echo "PR already exists or could not be created"