ame: Add Test Comment on Push

on:
  push:
    branches-ignore:
      - main  # Avoid infinite loops

jobs:
  add-test-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get modified files
        id: changed-files
        run: |
          # List modified files from the commit
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > modified_files.txt
          cat modified_files.txt
          
      - name: Add test comment to files
        run: |
          # Add "test" to the end of each modified file
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Adding test to $file"
              echo -e "\ntest" >> "$file"
            fi
          done < modified_files.txt
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add test comment to modified files
          branch: add-test-comment
          delete-branch: true
          base: main
          title: "Add test comment to modified files"
          body: |
            This PR adds a "test" comment at the end of files modified in the latest push.
            
            Automatically created by GitHub Actions.