name: Ailof

on:
  workflow_dispatch:
    inputs:
      flist_path:
        description: "Path to the flist file"
        required: true
        type: string
      vcd_path:
        description: "Path to the VCD file"
        required: true
        type: string

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for private repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AILOF_SSH_KEY }}
      
      - name: Clone ailof repository
        run: |
          git clone git@github.com:texerai/ailof.git
          cd ailof
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Set Environment Variables
        run: |
          echo "CVA6_REPO_DIR=${{ github.workspace }}/cva6" >> $GITHUB_ENV
          echo "TARGET_CFG=build" >> $GITHUB_ENV
          echo "HPDCACHE_DIR=${{ github.workspace }}/cva6/core/cache_subsystem/hpdcache" >> $GITHUB_ENV

      - name: Run Python Script
        run: |
          FLIST_PATH="${{ github.workspace }}/${{ inputs.flist_path }}"
          VCD_PATH="${{ github.workspace }}/${{ inputs.vcd_path }}"
          python ailof.py "${{ inputs.flist_path }}" "${{ inputs.vcd_path }}"


