name: Ailof

on:
  push:
    branches:
      - main

permission:
  contents: write
  pull-requests: write

jobs:
  ailof:
    name: ailof
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for private repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AILOF_SSH_KEY }}
      
      - name: Clone ailof repository
        run: |
          git clone git@github.com:your-org/ailof.git
          cd ailof
          # If you need a specific branch or tag
          # git checkout specific-branch-or-tag





